# Generated by Django 2.2 on 2019-04-10 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='contents',
            field=ckeditor.fields.RichTextField(verbose_name='内容'),
        ),
    ]
